---
title: "UFC RESEARCH QUESTION 1 LOG TRANSFORM"
author: ""
subtitle: "Due 5th December, 2024"
format: pdf
editor: 
  markdown: 
    wrap: 72
---

```{r}
# Import the CSV into R
ufc <- read.csv("ufc-master.csv")

# View the data
head(ufc)
```

```{r}
filtered_ufc_blue = ufc[!is.na(ufc$BlueAvgSigStrLanded), 
                        c("BlueReachCms","BlueAvgSigStrLanded","WeightClass")]
colnames(filtered_ufc_blue) <- c("ReachCms", "AvgSigStrLanded", "WeightClass")
filtered_ufc_red = ufc[!is.na(ufc$RedAvgSigStrLanded), 
                       c("RedReachCms","RedAvgSigStrLanded","WeightClass")]
colnames(filtered_ufc_red) <- c("ReachCms", "AvgSigStrLanded", "WeightClass")

# appending the two data sets
filtered_ufc = rbind(filtered_ufc_blue, filtered_ufc_red)

# exclude outlier(one observation with 0 cm reach)
filtered_ufc = filtered_ufc[filtered_ufc$ReachCms > 0,]
filtered_ufc <- filtered_ufc[filtered_ufc$AvgSigStrLanded > 0, ]
head(filtered_ufc)
```

```{r}
filtered_ufc$WeightClass = factor(filtered_ufc$WeightClass)

model = lm(AvgSigStrLanded ~ ReachCms * WeightClass, data = filtered_ufc)

summary(model)
```

```{r}
par(mfrow = c(2, 2), mar = c(2, 2, 2, 2)) 
plot(model)  
```





```{r}
library(nlme)
weights <- 1 / fitted(model)^2
model_wls <- lm(AvgSigStrLanded~ ReachCms * WeightClass, data = filtered_ufc, weights = weights)
par(mfrow = c(2, 2), mar = c(2, 2, 2, 2))
plot(model_wls)
```

